### PR TITLE
[DOC] README rocksdb version

### PR DESCRIPTION
**Pull request by raphaelauv**

### CODE REVIEW

**Comment by raphaelauv** [comment]
@mahnerak could you please review , thanks

**Review by mahnerak — APPROVED** [review]
LGTM

**Comment by raphaelauv** [comment]
@mahnerak let's merge ? thanks

**Comment by raphaelauv** [comment]
@mahnerak ?

**Comment by mahnerak** [comment]
Thanks @raphaelauv!

**Pull request merged**
